FROM ubuntu:18.04

MAINTAINER JYT 'jytprogramming@gmail.com'

WORKDIR /trendup/n_shopping

RUN apt-get update -y\
        &&apt-get install vim -y\
        &&apt-get upgrade -y\
        &&apt-get install python -y\
        &&apt-get install python-pip -y\
        &&apt-get install git -y\
        &&apt-get install python3 -y\
        &&apt-get install python3-pip -y

RUN pip3 install Beautifulsoup4\
        &&pip3 install requests\
        &&pip3 install pymysql

RUN git clone https://github.com/amkorousagi/Trendup.git

EXPOSE 5001/tcp
EXPOSE 5002/tcp
EXPOSE 5003/tcp
EXPOSE 5004/tcp
EXPOSE 5005/tcp
EXPOSE 5006/tcp
EXPOSE 5007/tcp
EXPOSE 5008/tcp
EXPOSE 5009/tcp
EXPOSE 5010/tcp



CMD /bin/bash
