FROM ubuntu:18.04

# install tools
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y git
RUN apt-get install -y vim
RUN apt-get install -y python-pip
RUN apt-get install -y python3-pip

RUN pip3 install langdetect
RUN pip3 install --upgrade google-cloud-language
RUN pip3 install requests
RUN pip3 install pymysql

# download code
RUN git clone https://github.com/amkorousagi/Trendup.git
WORKDIR /Trendup

# environment
EXPOSE 5001/tcp
EXPOSE 5002/tcp
EXPOSE 5003/tcp
EXPOSE 5004/tcp
EXPOSE 5005/tcp
EXPOSE 5006/tcp
EXPOSE 5007/tcp
EXPOSE 5008/tcp
EXPOSE 5009/tcp
EXPOSE 5010/tcp

# when run builded image
# CMD
# ENTRYPOINT /bin/bash

# when run
# docker run --rm -it -p <external port>:<container port> --name <container name> <docker imamge id or name> <command>
