FROM ubuntu:18.04

MAINTAINER JYT 'jytprogramming@gmail.com'

WORKDIR /trendup/n_shopping

RUN apt-get update -y\
        &&apt-get install vim -y\
        &&apt-get upgrade -y\
        &&apt-get install python -y\
        &&apt-get install python-pip -y\
        &&apt-get install git -y\
        &&apt-get install python3 -y\
        &&apt-get install python3-pip -y

RUN pip3 install beautifulsoup4\
        &&pip install requests\
        &&pip install pymysql

RUN git clone https://github.com/amkorousagi/Trendup.git

CMD /bin/bash
